name: Knox
options:
  bundleIdPrefix: com.knox
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES

targets:
  Knox:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Flapsy
        excludes:
          - "*.entitlements"
    settings:
      base:
        DEVELOPMENT_TEAM: W6XTHDJ64R
        PRODUCT_BUNDLE_IDENTIFIER: com.knox.app
        INFOPLIST_FILE: Flapsy/Info.plist
        CODE_SIGN_ENTITLEMENTS: Flapsy/Flapsy.entitlements
        PRODUCT_NAME: Knox
        MARKETING_VERSION: "1.6.1"
        CURRENT_PROJECT_VERSION: "22"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_OBJC_BRIDGING_HEADER: Flapsy/Flapsy-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/Flapsy/Crypto/Argon2"
          - "$(SRCROOT)/Flapsy/Crypto/Argon2/blake2"
        GCC_PREPROCESSOR_DEFINITIONS:
          - "$(inherited)"
          - "A2_VISCTL=1"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
    info:
      path: Flapsy/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSUIElement: true
        LSApplicationCategoryType: public.app-category.utilities
        NSHumanReadableCopyright: "Copyright © 2026 Knox. All rights reserved."
        NSFaceIDUsageDescription: "Knox uses Touch ID to quickly unlock your vault."
    entitlements:
      path: Flapsy/Flapsy.entitlements
      properties:
        com.apple.security.app-sandbox: false
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.knox.app"
